title: Emma Hawley | Microscopy
description: A collection of microscopy art
remote_theme: yousinix/portfolYOU

baseurl: "" 
url: "https://tawleyhawley.github.io"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
