title: Emma Hawley | Microscopy
description: A collection of microscopy art
remote_theme: yousinix/portfolYOU

baseurl: "https://tawleyhawley.github.io/website/" 
url: "https://tawleyhawley.github.io/website/"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
